TypeError: Cannot read property 'setVolume' of undefined Getting several of these in my crash reporter. Since the `volume` setter is already type-safe and removes the need to pass the value redundantly, this also makes it cleaner. ``` Exception com.tns.NativeScriptException: Calling js method onAudioFocusChange failed TypeError: Cannot read property 'setVolume' of undefined File: "<embedded>, line: 36, column: 2103308 StackTrace: Frame: function:'onAudioFocusChange', file:'<embedded>', line: 36, column: 2103309 com.tns.Runtime.callJSMethodNative (Runtime.java) com.tns.Runtime.dispatchCallJSMethodNative (Runtime.java:1088) com.tns.Runtime.callJSMethodImpl (Runtime.java:970) com.tns.Runtime.callJSMethod (Runtime.java:957) com.tns.Runtime.callJSMethod (Runtime.java:941) com.tns.Runtime.callJSMethod (Runtime.java:933) com.tns.gen.android.media.AudioManager_OnAudioFocusChangeListener.onAudioFocusChange (AudioManager_OnAudioFocusChangeListener.java:11) android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage (AudioManager.java:2358) android.os.Handler.dispatchMessage (Handler.java:102) android.os.Looper.loop (Looper.java:211) android.app.ActivityThread.main (ActivityThread.java:5371) java.lang.reflect.Method.invoke (Method.java) java.lang.reflect.Method.invoke (Method.java:372) com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:945) com.android.internal.os.ZygoteInit.main (ZygoteInit.java:740) ```